spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nguyenvannga
    username: nguyenvannga
    password:

  jpa:
    hibernate:
      ddl-auto: update # Tự động update schema khi thay đổi entity
    show-sql: true # Hiển thị câu SQL trong console

  thymeleaf:
    cache: false # Template không cache → reload khi chỉnh sửa

  devtools:
    restart:
      enabled: true # DevTools restart
    livereload:
      enabled: true # LiveReload hỗ trợ refresh browser
